#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the solve function below.
def solve(s):
    str = s.split(' ')
    return (' '.join((word.capitalize() for word in str)))

if __name__ == '__main__':
    s = input()

    result = solve(s)

    print(result)
